networks:
  editapp:

services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - editapp

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    networks:
      - editapp