networks:
  editapp:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - golang
      - python
    networks:
      - editapp

  golang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - editapp

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    ports:
      - "5000:5000"
    networks:
      - editapp