services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - python
    networks:
      - app-network

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    expose:
      - "5000"  # Экспонируем порт только внутри сети Docker, чтобы Go-сервер мог обращаться к нему
    networks:
      - app-network

networks:
  app-network:
    driver: bridge