networks:
  editapp:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - localhost
      - python
    networks:
      - editapp

  localhost:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - editapp

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    networks:
      - editapp