version: '3.8'

services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    volumes:
      - ./www:/www

  python:
    build:
      context: .
      dockerfile: DockerfilePython
    ports:
      - "5000:5000"
    networks:
      - app-network
    volumes:
      - ./www:/www

networks:
  app-network:
    driver: bridge