version: '3.8'

services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  python:
    build:
      context: .
      dockerfile: Dockerfile-python
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge